# dataset locations

# === Project root
project_root: &root /Users/ntin/Documents/DermaML_local/hawkeye-hands-2024-07-29
# join child folders with syntax `!join [*root, /path]`


# === Output
output_dir: !join [*root, /results/]

# === Processed images
image_dir: !join [*root, /images_processed/]
image_extension: .png

# === Metadata
metadata_file: !join [*root, /metadata.csv]
metadata_ref_header: hand_image_file
metadata_ref_extension: .jpeg

# === Image Segmentation
segmentation_file: /Users/ntin/Models/sam2/notebooks/2025-02-23_Hand_Segmentations-Corrected-3.pkl

# === Tabular data
# FIXME index files specifically from here
tabular_feature_file: !join [*root, /features-2025-02-24/]
tabular_ref_header: filename
tabular_ref_extension: .png