# dataset locations
# child folders are joined with syntax `!join [*root, /path]`


# === Project root paths
project_root: &projroot /Users/ntin/DermaML/data/
img_root: &imgroot /Users/ntin/Documents/DermaML_local/hawkeye-hands-2024-07-29

paths:
    # -- Output
    output_dir: !join [*imgroot, /results/]
    # -- Processed images
    image_dir: !join [*imgroot, /images_processed/]
    # -- Metadata
    metadata_file: !join [*projroot, 2025-03-15-Grouped_Data/2025-03-15-NT-metadata_over_40_only_splitted.csv]
    # -- Tabular data
    # FIXME index files specifically from here
    tabular_feature_file: !join [*projroot, /2025-02-24-hawkeye_hands-combined_tabular_features.csv]
    # -- Image Segmentation
    segmentation_file: !join [*projroot, 2025-02-23_Hand_Segmentations-Corrected-3.pkl]

# === Processed images
image_extension: .png

# === Metadata
metadata_ref_header: hand_image_file
metadata_ref_hand: hand
metadata_ref_extension: .jpeg
metadata_target: age

# === Tabular data
tabular_ref_header: filename
tabular_ref_hand: handedness
tabular_ref_extension: .png # might need to be empty string''
tabular_ref_target: Age
